import csv; import re
import argparse
import get_iv_cv_dicts as dicts
import os
import pandas as pd

parser=argparse.ArgumentParser(description='Covert test results to xml schemas')
parser.add_argument('--f', type=str, help='the .txt filname', required=False)
parser.add_argument('--t', type=str, help='the XML: Tablename you wish to priduce. Available options are: [HGC_CERN_SENSOR_IV,HGC_CERN_SENSOR_IV_SUMRY]', required=False)
parser.add_argument('--setup', type=bool, help='boolean to say whether you have done source ./setup.sh', required=False)

parser.add_argument('--user', type=str, help='The name of the user who did this test. Default is Alex.', required=False, default='Alex')
parser.add_argument('--location', type=str, help='The locatino where this test was carried. Default is "FSU"', required=False, default='FSU')
parser.add_argument('--comment', type=str, help='Any comments on this test. Default is the comment from the .txt file', required=False,default = True)

args = parser.parse_args()


################################################## CONFIGURATIONS ########################################################

filename = args.f
XML_tablename=args.t
SETUP = args.setup

PRESERIES=True

#YOU HAVE TO DO 
#source ./setup.sh
#in the base directory, which sets up these environment variables. 
#if you don't want to set it up (just for testing) do --steup False at the end of running this file
try:
    FSUDB_OUTPUT_DIR=os.environ['FSUDB_OUTPUT_DIR']

    PRESERIES_IV_SUMMARY_DIR = os.environ['PRESERIES_IV_SUMMARY_DIR']
    OLD_PRESERIES_IV_SUMMARY_DIR = os.environ['OLD_PRESERIES_IV_SUMMARY_DIR']


    PRESERIES_CV_SUMMARY_DIR = os.environ['PRESERIES_CV_SUMMARY_DIR']
    OLD_PRESERIES_CV_SUMMARY_DIR = os.environ['OLD_PRESERIES_CV_SUMMARY_DIR']
    print('All environment variables properly set!')

except KeyError:
    #raise KeyError(key) from None
    print("you haven't set up any environemnt variables for your resutls! Set the environment variables in setup.sh and do source ./setup.sh") 
    pass


#### GET FULL PATHS OF LCD SUMMARY DIRS
if PRESERIES:
    IV_SUMMARY_FULL_DIRS=[]
    for dir in os.listdir(PRESERIES_IV_SUMMARY_DIR):
        IV_SUMMARY_FULL_DIRS.append(os.path.join(PRESERIES_IV_SUMMARY_DIR, dir))
    for dir in os.listdir(OLD_PRESERIES_IV_SUMMARY_DIR):
        IV_SUMMARY_FULL_DIRS.append(os.path.join(OLD_PRESERIES_IV_SUMMARY_DIR, dir))       
    
    CV_SUMMARY_FULL_DIRS=[]
    for dir in os.listdir(PRESERIES_CV_SUMMARY_DIR):
        CV_SUMMARY_FULL_DIRS.append(os.path.join(PRESERIES_CV_SUMMARY_DIR, dir))
    for dir in os.listdir(OLD_PRESERIES_CV_SUMMARY_DIR):
        CV_SUMMARY_FULL_DIRS.append(os.path.join(OLD_PRESERIES_CV_SUMMARY_DIR, dir))  
print('IV_SUMMARY_FULL_DIRS= ', IV_SUMMARY_FULL_DIRS)


#### GET FULL PATHS OF LCD HGSENSOR DIRS
if PRESERIES:
    IV_HGSENSOR_FULL_DIRS=[]
    for dir in os.listdir(PRESERIES_IV_HGSENSOR_DIR):
        IV_HGSENSOR_FULL_DIRS.append(os.path.join(PRESERIES_IV_HGSENSOR_DIR, dir))
    for dir in os.listdir(OLD_PRESERIES_IV_HGSENSOR_DIR):
        IV_HGSENSOR_FULL_DIRS.append(os.path.join(OLD_PRESERIES_IV_HGSENSOR_DIR, dir))       
    
    CV_HGSENSOR_FULL_DIRS=[]
    for dir in os.listdir(PRESERIES_CV_HGSENSOR_DIR):
        CV_HGSENSOR_FULL_DIRS.append(os.path.join(PRESERIES_CV_HGSENSOR_DIR, dir))
    for dir in os.listdir(OLD_PRESERIES_CV_HGSENSOR_DIR):
        CV_HGSENSOR_FULL_DIRS.append(os.path.join(OLD_PRESERIES_CV_HGSENSOR_DIR, dir))  
print('IV_HGSENSOR_FULL_DIRS= ', IV_HGSENSOR_FULL_DIRS)




################################################### GET STUFF YOU NEED FROM SUMMARY DIRECTORIES (GENERATED BY https://gitlab.cern.ch/CLICdp/HGCAL/lcd_hgcal_analysisworkflows) #########################################################

def get_kind_of_part(scratchpad_ID, IV_or_CV):
    scratchpad_ID=scratchpad_ID.split('_')[0]
    #search the summary directories for this scratcpadid then find the tex file
    if IV_or_CV=="IV":
        for fullpath in IV_SUMMARY_FULL_DIRS:
            if scratchpad_ID in fullpath:
                scratchpad_ID_fullpath=fullpath
                print('\n scratchpadID path=', scratchpad_ID_fullpath)
                for file in os.listdir(scratchpad_ID_fullpath):
                    if file.endswith('.tex') and "elog" not in file:
                        summary_tex_file_path=os.path.join(scratchpad_ID_fullpath, file)
                        print('\n SUMMARY TEX FILE', summary_tex_file_path)
                        f_tex=open(summary_tex_file_path,'r')
                        for line in f_tex:
                            if "item active thickness:" in line:
                                print('thickness=', line.split()[3])
                                thickness= int(line.split()[3])
                        f_tex.close()

    if IV_or_CV=="CV":
        for fullpath in CV_SUMMARY_FULL_DIRS:
            if scratchpad_ID in fullpath:
                scratchpad_ID_fullpath=fullpath
                print('\n scratchpadID path=', scratchpad_ID_fullpath)
                for file in os.listdir(scratchpad_ID_fullpath):
                    if file.endswith('.tex') and "elog" not in file:
                        summary_tex_file_path=os.path.join(scratchpad_ID_fullpath, file)
                        print('\n SUMMARY TEX FILE', summary_tex_file_path)
                        f_tex=open(summary_tex_file_path,'r')
                        for line in f_tex:
                            if "item active thickness:" in line:
                                print('thickness=', line.split()[3])
                                thickness= int(line.split()[3])
                        f_tex.close()

    if thickness==120:
        HDorLD='HD'
    elif thickness==200:
        HDorLD='LD'
    elif thickness==300:
        HDorLD='LD'
    else:
        print('couldnt find the thickness for sensor with %d scratchpad_ID (serial number)' % scratchpad_ID)
    kind_of_part= str(thickness)+ 'um Si Sensor ' +  HDorLD + ' Full'
    print('kind of part = ', kind_of_part)
    return kind_of_part

###################################################
def GET_GRADING_CRITERIA_IV(scratchpad_ID):
    scratchpad_ID=scratchpad_ID.split('_')[0]
    #search the summary directories for this scratcpadid then find the tex file
    #BAD BADS ARE STORED IN EG "/home/output/hgsensor_iv/grading/N3313_9_DF/bad_pads.txt"
    for fullpath in IV_SUMMARY_FULL_DIRS:
        if scratchpad_ID in fullpath:
            scratchpad_ID_fullpath=fullpath
            print('\n scratchpadID path=', scratchpad_ID_fullpath)
            for file in os.listdir(scratchpad_ID_fullpath):
                if file.endswith('.tex') and "elog" not in file:
                    summary_tex_file_path=os.path.join(scratchpad_ID_fullpath, file)
                    print('\n SUMMARY TEX FILE IV', summary_tex_file_path)
                    f_tex=open(summary_tex_file_path,'r')
                    for line in f_tex:
                        if "item Number of bad pads 0 <= 8 for full-sized sensors:" in line:
                            print(line.split())
                            if "Passed" in line:
                                NUM_BAD_CELLS_PASS = "PASSED"
                            else:
                                NUM_BAD_CELLS_PASS = "FAILED"
                            print("NUM_BAD_CELLS_PASS=", NUM_BAD_CELLS_PASS)

                        if "item Current at 600V I600 (normalised to 20 deg Celsius): <= 100 $\mu$A integrated over the sensor and guard rings" in line:
                            print(line.split())
                            if "Passed" in line:
                                CURNT_600V_LESSTHAN_100uA = "PASSED"
                            else:
                                CURNT_600V_LESSTHAN_100uA = "FAILED"
                            print('CURNT_600V_LESSTHAN_100uA=', CURNT_600V_LESSTHAN_100uA)

                        if "item I800 < 2.5 x I600:" in line:
                            print(line.split())
                            if "Passed" in line:
                                CURNT_800V_LESSTHAN_2POINT5_CURNT_600V = "PASSED"
                            else:
                                CURNT_800V_LESSTHAN_2POINT5_CURNT_600V="FAILED"
                            print("CURNT_800V_LESSTHAN_2POINT5_CURNT_600V", CURNT_800V_LESSTHAN_2POINT5_CURNT_600V)

                        if "item Allowed number of adjacent bad pads <= 2:" in line:
                            print(line.split())
                            if "Passed" in line:
                                NUM_BAD_ADJ_CELLS_PASS = "PASSED"
                            else:
                                NUM_BAD_ADJ_CELLS_PASS = "FAIL"
                            print("NUM_BAD_ADJ_CELLS_PASS", NUM_BAD_ADJ_CELLS_PASS)
                        if "the requirements" in line:
                            if "PASSED" in line:
                                PASS = 'Y'
                            else:
                                PASS='N'
                            print("PASS", PASS)
                    f_tex.close()

    return NUM_BAD_CELLS_PASS, CURNT_600V_LESSTHAN_100uA, CURNT_800V_LESSTHAN_2POINT5_CURNT_600V, NUM_BAD_ADJ_CELLS_PASS, PASS






################################################### GET STUFF YOU NEED FROM HGSENSOR DIRECTORIES (GENERATED BY https://gitlab.cern.ch/CLICdp/HGCAL/lcd_hgcal_analysisworkflows) #########################################################

def get_number_bad_cells(scratchpad_ID, IV_or_CV):
    scratchpad_ID=scratchpad_ID.split('_')[0]
    #search the HGSENSOR directories for this scratcpadid then find the tex file
    if IV_or_CV=="IV":
        for fullpath in IV_HGSENSOR_FULL_DIRS:
            if scratchpad_ID in fullpath:
                scratchpad_ID_fullpath=fullpath
                print('\n scratchpadID path=', scratchpad_ID_fullpath)
                for file in os.listdir(scratchpad_ID_fullpath):
                    if file == 'bad_pads.tex':
                        hgsensor_tex_file_path=os.path.join(scratchpad_ID_fullpath, file)
                        print('\n HGSENSOR TEX FILE', hgsensor_tex_file_path)
                        f_tex=open(hgsensor_tex_file_path,'r')
                        num_bad_pads = len(f_tex.readlines())
                        print('NUMBER OF BAD PADS='num_bad_pads)

                        f_tex.close()

    if IV_or_CV=="CV":
        for fullpath in CV_HGSENSOR_FULL_DIRS:
            if scratchpad_ID in fullpath:
                scratchpad_ID_fullpath=fullpath
                print('\n scratchpadID path=', scratchpad_ID_fullpath)
                for file in os.listdir(scratchpad_ID_fullpath):
                    if file.endswith('.tex') and "elog" not in file:
                        hgsensor_tex_file_path=os.path.join(scratchpad_ID_fullpath, file)
                        print('\n HGSENSOR TEX FILE', hgsensor_tex_file_path)
                        f_tex=open(hgsensor_tex_file_path,'r')
                        num_bad_pads = len(f_tex.readlines())
                        f_tex.close()


####################################################################################################

def convert_timestamp(orig_format):                                                                                                                                              
    '''
    orig_format example = 15.8.2022 12:39                                                                                                                                           
    desired_format example=2012-09-19 14:04:00 '''                                                                                                                                       
    #print('original time', orig_format)                                                                                                                                         
    date, time = orig_format.split()                                                                                                                                             
    day, month, year = date.split('.')                                                                                                                                           
    month='0'+month if len(month)==1 else month                                                                                                                                  
    hour, minutes = time.split(':')                                                                                                                                              
    desired_format = year+'-'+month+'-'+day+' '+ hour+':'+minutes+':00' #an f string would have been so much nicer! (but lcd uses python 2)                                                                                                                
    #print(desired_format)                                                                                                                                                       
    return desired_format 

def get_TOT_CURRENT_600_800V(DICT):
    """ DICT could be IVDICT or CVDICT
    To use: TOT_CURRENT_600, TOT_CURRENT_800 = get_TOT_CURRENT(IVDICT)
    """
    DF = pd.DataFrame.from_dict(DICT)
    mask_600 = DF[DF['V_list']==str(-600.0)]
    TOT_CURRENT_600 = DF[mask_600]['Tot_Current_list'][0]
    mask_800 = DF[DF['V_list']==str(-800.0)]
    TOT_CURRENT_800 = DF[mask_800]['Tot_Current_list'][0]
    return TOT_CURRENT_600, TOT_CURRENT_800

####################################################################################################





##################### #####################  IV TABLES #####################  ##################### 

def make_xml_schema_HGC_CERN_SENSOR_IV(filename):
    
    IVDICT = dicts.get_iv_dict(filename)
    XML_tablename = 'HGC_CERN_SENSOR_IV'

    Name = 'HGC Sensor Manufacturer IV'
    Sensor_Type = IVDICT['Sensor_type']
    Run_Name = IVDICT['Identifier'].split('_')[0]
    location=args.location
    # Kind_of_part = '200um Si Sensor SD Full'

    serial_number =IVDICT['Scratchpad_ID'] #+Run_Name#REMEMBER, SERIAL NUMBER IS SCRATCHPAD ID
    if PRESERIES:
        serial_number = serial_number +'_0'

    Kind_of_part = get_kind_of_part(serial_number, "IV")

    xml_table_file = FSUDB_OUTPUT_DIR + Run_Name + '_'+ XML_tablename + '_PRESERIES_TEST.xml'

    with open(xml_table_file, 'w+') as xmlf:
        xmlf.write('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n')
        xmlf.write('<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n')
        xmlf.write('<HEADER>\n')
        xmlf.write('\t<TYPE>\n')
        xmlf.write('\t\t<EXTENSION_TABLE_NAME>HGC_CERN_SENSOR_IV</EXTENSION_TABLE_NAME>\n')
        xmlf.write('\t\t<NAME>HGC CERN Sensor IV</NAME>\n')
        xmlf.write('\t</TYPE>\n')
        xmlf.write('\t\t<RUN>\n')
        xmlf.write('\t\t\t<RUN_NAME>' + Run_Name + '</RUN_NAME>\n')
        xmlf.write('\t\t\t<RUN_BEGIN_TIMESTAMP>'+convert_timestamp(IVDICT['Timestamp'].replace("\n", "").rstrip())+'</RUN_BEGIN_TIMESTAMP>\n')
        xmlf.write('\t\t\t<RUN_END_TIMESTAMP>'+convert_timestamp(IVDICT['Timestamp'].replace("\n", "").rstrip())+'</RUN_END_TIMESTAMP>\n')
        xmlf.write('\t\t\t<INITIATED_BY_USER>'+args.user.rstrip()+'</INITIATED_BY_USER>\n')
        xmlf.write('\t\t\t<LOCATION>'+location.rstrip()+'</LOCATION>\n')
        if args.comment:
            xmlf.write('\t\t\t<COMMENT_DESCRIPTION>'+args.comment.replace("\n", "").rstrip()+ '</COMMENT_DESCRIPTION>\n')
        else:
            xmlf.write('\t\t\t<COMMENT_DESCRIPTION>'+str(IVDICT['Comments']).replace("\n", "").rstrip()+ '</COMMENT_DESCRIPTION>\n')
        xmlf.write('\t\t</RUN>\n')
        xmlf.write(' </HEADER>\n')

        xmlf.write('\t\t<DATA_SET>\n')
        xmlf.write('\t\t\t<PART>\n')
        xmlf.write('\t\t\t\t<KIND_OF_PART>'+Kind_of_part.rstrip()+'</KIND_OF_PART>\n')
        xmlf.write('\t\t\t\t<SERIAL_NUMBER>'+serial_number.rstrip()+'</SERIAL_NUMBER>\n')
        xmlf.write('\t\t\t</PART>\n')


        for i in range(len(IVDICT['V_list'])):
            xmlf.write('\t\t\t<DATA>\n')
            xmlf.write('\t\t\t\t<VOLTS>'+str(IVDICT['V_list'][i]).rstrip()+'</VOLTS>\n')
            #BELLOW IS CHANNEL CURRENT
            xmlf.write('\t\t\t\t<CURNT_NANOAMP>'+str(IVDICT['Channel_Current_list'][i]).rstrip()+'</CURNT_NANOAMP>\n')
            #BLLOW IS CHANNEL ERROR CURRENT
            xmlf.write('\t\t\t\t<ERR_CURNT_NANOAMP>'+str(IVDICT['Error_Current_list'][i]).rstrip()+'</ERR_CURNT_NANOAMP>\n')
            #BELLOW IS TOT CURRENT 
            xmlf.write('\t\t\t\t<TOT_CURNT_NANOAMP>'+str(IVDICT['Tot_Current_list'][i]).rstrip()+'</TOT_CURNT_NANOAMP>\n')
            xmlf.write('\t\t\t\t<ACTUAL_VOLTS>'+str(IVDICT['Act_Volts_list'][i]).rstrip()+'</ACTUAL_VOLTS>\n')
            xmlf.write('\t\t\t\t<TIME_SECS>'+str(IVDICT['Time_list'][i]).rstrip()+'</TIME_SECS>\n')
            xmlf.write('\t\t\t\t<TEMP_DEGC>'+str(IVDICT['Temp_list'][i]).rstrip()+'</TEMP_DEGC>\n')
            xmlf.write('\t\t\t\t<HUMIDITY_PRCNT>'+str(IVDICT['Humidity_list'][i]).rstrip()+'</HUMIDITY_PRCNT>\n')
            # xmlf.write('\t\t\t\t<HUMIDITY_PRCNT>'+str(0.000000E+0)	+'</HUMIDITY_PRCNT>\n')

            xmlf.write('\t\t\t\t<CELL_NR>'+str(IVDICT['Cell_Number_list'][i]).rstrip()+'</CELL_NR>\n')
            xmlf.write('\t\t\t</DATA>\n')

        
        xmlf.write('\t\t</DATA_SET>\n')
        xmlf.write('</ROOT>\n')


                    

#################################################### CV TABLES ######################################################3


def make_xml_schema_HGC_CERN_SENSOR_CV(filename):

    CVDICT = dicts.get_cv_dict(filename)
    XML_tablename = 'HGC_CERN_SENSOR_CV'

    Name = 'HGC Sensor Manufacturer IV'
    Run_Name = CVDICT['Identifier'].split('_')[0]
    location=args.location
    # Kind_of_part = '200um Si Sensor SD Full'
    serial_number =CVDICT['Scratchpad_ID'] #+Run_Name#REMEMBER, SERIAL NUMBER IS SCRATCHPAD ID
    if PRESERIES:
        serial_number = serial_number +'_0'

    Kind_of_part = get_kind_of_part(serial_number, "CV")

    xml_table_file = FSUDB_OUTPUT_DIR + Run_Name + '_'+ XML_tablename + '_PRESERIES.xml'

    with open(xml_table_file, 'w+') as xmlf:
        xmlf.write('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n')
        xmlf.write('<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n')
        xmlf.write('<HEADER>\n')
        xmlf.write('\t<TYPE>\n')
        xmlf.write('\t\t<EXTENSION_TABLE_NAME>HGC_CERN_SENSOR_CV</EXTENSION_TABLE_NAME>\n')
        xmlf.write('\t\t<NAME>HGC CERN Sensor CV</NAME>\n')
        xmlf.write('\t</TYPE>\n')
        xmlf.write('\t\t<RUN>\n')
        xmlf.write('\t\t\t<RUN_NAME>' + Run_Name.rstrip() + '</RUN_NAME>\n')
        xmlf.write('\t\t\t<RUN_BEGIN_TIMESTAMP>'+convert_timestamp(CVDICT['Timestamp'].replace("\n", "").rstrip())+'</RUN_BEGIN_TIMESTAMP>\n')
        xmlf.write('\t\t\t<RUN_END_TIMESTAMP>'+convert_timestamp(CVDICT['Timestamp'].replace("\n", "").rstrip())+'</RUN_END_TIMESTAMP>\n')
        xmlf.write('\t\t\t<INITIATED_BY_USER>'+args.user.rstrip()+'</INITIATED_BY_USER>\n')
        xmlf.write('\t\t\t<LOCATION>'+location.rstrip()+'</LOCATION>\n')
        if args.comment:
            xmlf.write('\t\t\t<COMMENT_DESCRIPTION>'+args.comment.rstrip()+ '</COMMENT_DESCRIPTION>\n')
        else:
            xmlf.write('\t\t\t<COMMENT_DESCRIPTION>'+str(CVDICT['Comments']).replace("\n", "").rstrip()+ '</COMMENT_DESCRIPTION>\n')
        xmlf.write('\t\t</RUN>\n')
        xmlf.write(' </HEADER>\n')

        xmlf.write('\t\t<DATA_SET>\n')
        xmlf.write('\t\t\t<PART>\n')
        xmlf.write('\t\t\t\t<KIND_OF_PART>'+Kind_of_part.rstrip()+'</KIND_OF_PART>\n')
        xmlf.write('\t\t\t\t<SERIAL_NUMBER>'+serial_number.rstrip()+'</SERIAL_NUMBER>\n')
        xmlf.write('\t\t\t</PART>\n')


        for i in range(len(CVDICT['V_list'])):
            xmlf.write('\t\t\t<DATA>\n')
            xmlf.write('\t\t\t\t<VOLTS>'+str(CVDICT['V_list'][i]).rstrip()+'</VOLTS>\n')
            xmlf.write('\t\t\t\t<CPCTNCE_PFRD>'+str(CVDICT['Cs_list'][i]).rstrip()+'</CPCTNCE_PFRD>\n')
            xmlf.write('\t\t\t\t<ERR_CPCTNC_PFRD>'+str(CVDICT['Error_capacitance_list'][i]).rstrip()+'</ERR_CPCTNC_PFRD>\n')

            xmlf.write('\t\t\t\t<TOT_CURNT_NANOAMP>'+str(CVDICT['Tot_Current_list'][i]).rstrip()+'</TOT_CURNT_NANOAMP>\n')

            xmlf.write('\t\t\t\t<ACTUAL_VOLTS>'+str(CVDICT['Act_Volts_list'][i]).rstrip()+'</ACTUAL_VOLTS>\n')
            xmlf.write('\t\t\t\t<ORG_CPCTNC_PFRD>'+str(CVDICT['Cs_uncorr_list'][i]).rstrip()+'</ORG_CPCTNC_PFRD>\n')
            xmlf.write('\t\t\t\t<TEMP_DEGC>'+str(CVDICT['Temp_list'][i]).rstrip()+'</TEMP_DEGC>\n')
            xmlf.write('\t\t\t\t<HUMIDITY_PRCNT>'+str(CVDICT['Humidity_list'][i]).rstrip()+'</HUMIDITY_PRCNT>\n')
        # xmlf.write('\t\t\t\t<HUMIDITY_PRCNT>'+str(0.000000E+0)	+'<HUMIDITY_PRCNT>\n')
            xmlf.write('\t\t\t\t<IMP_OHM>'+str(CVDICT['Impedence_list'][i]).rstrip()+'</IMP_OHM>\n')
            xmlf.write('\t\t\t\t<PHS_RAD>'+str(CVDICT['Phase_list'][i]).rstrip()+'</PHS_RAD>\n')
            xmlf.write('\t\t\t\t<TIME_SECS>'+str(CVDICT['Time_list'][i]).rstrip()+'</TIME_SECS>\n')
            xmlf.write('\t\t\t\t<CELL_NR>'+str(CVDICT['Cell_Number_list'][i]).rstrip()+'</CELL_NR>\n')
            xmlf.write('\t\t\t</DATA>\n')


        
        xmlf.write('\t\t</DATA_SET>\n')
        xmlf.write('</ROOT>\n')





##################### #####################  IV SUMMARY TABLES #####################  ##################### 

def make_xml_schema_HGC_CERN_SENSOR_IV_SUMRY(filename):
    """
    This generates An output XML file, based on the HGCAL DB XML template for 
    HGC_CERN_SENSOR_IV_SUMRY from text files of sensor IV results generated by HEXDAQ
    
    Fields that this fills:
    <VOLTS> (removed)
    <TOT_CURNT_NANOAMP_600V>
    <TOT_CURNT_NANOAMP_800V>
    <NUM_BAD_CELLS>: integer 
    <PASS>: Y or N
    <GRADE> (REMOVED)
    <NUM_BAD_ADJ_CELLS>: integer
    <CURNT_600V_LESSTHAN_100uA>: PASS or FAIL
    <CURNT_800V_LESSTHAN_2POINT5_CURNT_600V>: PASS or FAIL
    <NUM_BAD_CELLS_PASS>: PASS or FAIL  from \item Number of bad pads 0 <= 8 for full-sized sensors: textcolor{green}{Passed})
    <NUM_BAD_ADJ_CELLS_PASS>: PASS or FAIL
    Args:s
        filename (.txt file): output file of HEXDAQ results
    """
    
    IVDICT = dicts.get_iv_dict(filename)
    XML_tablename = 'HGC_CERN_SENSOR_IV_SUMRY'

    Name = 'HGC Sensor Manufacturer IV'
    Sensor_Type = IVDICT['Sensor_type']
    Run_Name = IVDICT['Identifier'].split('_')[0]
    location=args.location
    # Kind_of_part = '200um Si Sensor SD Full' #example of the accepted format

    serial_number =IVDICT['Scratchpad_ID'] #+Run_Name#REMEMBER, SERIAL NUMBER IS SCRATCHPAD ID
    if PRESERIES:
        serial_number = serial_number +'_0'

    Kind_of_part = get_kind_of_part(serial_number, "IV")

    xml_table_file = FSUDB_OUTPUT_DIR + Run_Name + '_'+ XML_tablename + '_PRESERIES_TEST.xml'

    NUM_BAD_CELLS_PASS, CURNT_600V_LESSTHAN_100uA, CURNT_800V_LESSTHAN_2POINT5_CURNT_600V, NUM_BAD_ADJ_CELLS_PASS, PASS = GET_GRADING_CRITERIA_IV(serial_number)
    with open(xml_table_file, 'w+') as xmlf:
        xmlf.write('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n')
        xmlf.write('<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n')
        xmlf.write('<HEADER>\n')
        xmlf.write('\t<TYPE>\n')
        xmlf.write('\t\t<EXTENSION_TABLE_NAME>HGC_CERN_SENSOR_IV_SUMRY</EXTENSION_TABLE_NAME>\n')
        xmlf.write('\t\t<NAME>HGC CERN Sensor IV Summary</NAME>\n')
        xmlf.write('\t</TYPE>\n')
        xmlf.write('\t\t<RUN>\n')
        xmlf.write('\t\t\t<RUN_NAME>' + Run_Name + '</RUN_NAME>\n')
        xmlf.write('\t\t\t<RUN_BEGIN_TIMESTAMP>'+convert_timestamp(IVDICT['Timestamp'].replace("\n", "").rstrip())+'</RUN_BEGIN_TIMESTAMP>\n')
        xmlf.write('\t\t\t<RUN_END_TIMESTAMP>'+convert_timestamp(IVDICT['Timestamp'].replace("\n", "").rstrip())+'</RUN_END_TIMESTAMP>\n')
        xmlf.write('\t\t\t<INITIATED_BY_USER>'+args.user.rstrip()+'</INITIATED_BY_USER>\n')
        xmlf.write('\t\t\t<LOCATION>'+location.rstrip()+'</LOCATION>\n')
        # if args.comment:
        #     xmlf.write('\t\t\t<COMMENT_DESCRIPTION>'+args.comment.replace("\n", "").rstrip()+ '</COMMENT_DESCRIPTION>\n')
        # else:
        #     xmlf.write('\t\t\t<COMMENT_DESCRIPTION>'+str(IVDICT['Comments']).replace("\n", "").rstrip()+ '</COMMENT_DESCRIPTION>\n')
        xmlf.write('\t\t\t<COMMENT_DESCRIPTION>'+str(IVDICT['Comments']).replace("\n", "").rstrip()+ '</COMMENT_DESCRIPTION>\n')
        xmlf.write('\t\t</RUN>\n')
        xmlf.write(' </HEADER>\n')

        xmlf.write('\t\t<DATA_SET>\n')
        xmlf.write('\t\t\t<PART>\n')
        xmlf.write('\t\t\t\t<KIND_OF_PART>'+Kind_of_part.rstrip()+'</KIND_OF_PART>\n')
        xmlf.write('\t\t\t\t<SERIAL_NUMBER>'+serial_number.rstrip()+'</SERIAL_NUMBER>\n')
        xmlf.write('\t\t\t</PART>\n')


        xmlf.write('\t\t\t<DATA>\n')
        #ask if this is correct - this will be just a random cell at this voltage?
        xmlf.write('\t\t\t\t #############################################################################\n')
        xmlf.write('\t\t\t\t are these <TOT_CURNT_NANOAMP_600V> and  <TOT_CURNT_NANOAMP_800V> still a part of the template? If so, to which cells should they be recorded?\n') 
        TOT_CURRENT_600, TOT_CURRENT_800 = get_TOT_CURRENT(IVDICT)
        xmlf.write('\t\t\t\t<TOT_CURNT_NANOAMP_600V>'+TOT_CURRENT_600+'</TOT_CURNT_NANOAMP_600V>\n')
        xmlf.write('\t\t\t\t<TOT_CURNT_NANOAMP_800V>'+TOT_CURRENT_800+'</TOT_CURNT_NANOAMP_800V>\n')
        xmlf.write('\t\t\t\t #############################################################################\n')
        xmlf.write('\t\t\t\t<CURNT_600V_LESSTHAN_100uA>'+CURNT_600V_LESSTHAN_100uA+'</CURNT_600V_LESSTHAN_100uA>\n')
        xmlf.write('\t\t\t\t<CURNT_800V_LESSTHAN_2POINT5_CURNT_600V>'+CURNT_800V_LESSTHAN_2POINT5_CURNT_600V+'</CURNT_800V_LESSTHAN_2POINT5_CURNT_600V>\n')
        xmlf.write('\t\t\t\t<NUM_BAD_CELLS>'+ 'Is this a necessarry field to have? Its a bit harder to fetch' + '</NUM_BAD_CELLS>\n')
        xmlf.write('\t\t\t\t<NUM_BAD_CELLS_PASS>'+NUM_BAD_CELLS_PASS+'</NUM_BAD_CELLS_PASS>\n')
        xmlf.write('\t\t\t\t<PASS>'+PASS+'</PASS>\n')
        xmlf.write('\t\t\t\t<NUM_BAD_ADJ_CELLS_PASS>'+NUM_BAD_ADJ_CELLS_PASS+'</NUM_BAD_ADJ_CELLS_PASS>\n')
        xmlf.write('\t\t\t<DATA>\n')
        xmlf.write('\t\t</DATA_SET>\n')
        xmlf.write('</ROOT>\n')
        



    # #IF SAVING SUMMARY FOR EVERY CELL, UNCEOMMNET BELLOW
    # ################################################################################
    # #     for i in range(len(IVDICT['V_list'])):
    # #         xmlf.write('\t\t\t<DATA>\n')
    # #         xmlf.write('\t\t\t\t<VOLTS>'+str(IVDICT['V_list'][i]).rstrip()+'</VOLTS>\n')
    # #         #BELLOW IS CHANNEL CURRENT
    # #         xmlf.write('\t\t\t\t<CURNT_NANOAMP>'+str(IVDICT['Channel_Current_list'][i]).rstrip()+'</CURNT_NANOAMP>\n')
    # #         #BLLOW IS CHANNEL ERROR CURRENT
    # #         xmlf.write('\t\t\t\t<ERR_CURNT_NANOAMP>'+str(IVDICT['Error_Current_list'][i]).rstrip()+'</ERR_CURNT_NANOAMP>\n')
    # #         #BELLOW IS TOT CURRENT 
    # #         xmlf.write('\t\t\t\t<TOT_CURNT_NANOAMP>'+str(IVDICT['Tot_Current_list'][i]).rstrip()+'</TOT_CURNT_NANOAMP>\n')
    # #         xmlf.write('\t\t\t\t<ACTUAL_VOLTS>'+str(IVDICT['Act_Volts_list'][i]).rstrip()+'</ACTUAL_VOLTS>\n')
    # #         xmlf.write('\t\t\t\t<TIME_SECS>'+str(IVDICT['Time_list'][i]).rstrip()+'</TIME_SECS>\n')
    # #         xmlf.write('\t\t\t\t<TEMP_DEGC>'+str(IVDICT['Temp_list'][i]).rstrip()+'</TEMP_DEGC>\n')
    # #         xmlf.write('\t\t\t\t<HUMIDITY_PRCNT>'+str(IVDICT['Humidity_list'][i]).rstrip()+'</HUMIDITY_PRCNT>\n')
    # #         # xmlf.write('\t\t\t\t<HUMIDITY_PRCNT>'+str(0.000000E+0)	+'</HUMIDITY_PRCNT>\n')

    # #         xmlf.write('\t\t\t\t<CELL_NR>'+str(IVDICT['Cell_Number_list'][i]).rstrip()+'</CELL_NR>\n')
    # #         xmlf.write('\t\t\t</DATA>\n')
    # ################################################################################

        
    #     xmlf.write('\t\t</DATA_SET>\n')
    #     xmlf.write('</ROOT>\n')




                
if __name__ == '__main__':
    # if XML_tablename=='HGC_SENSOR_IV':
    #     Sensor_type, Timestamp, Run_name, V_list, Tot_Current_list = get_V_I_lists(filename)
    #     make_xml_schema_HGC_SENSOR_IV(Sensor_type, Timestamp, Run_name, V_list, I_list)
    # elif XML_tablename=='HGC_CERN_SENSOR_IV':         
    # filename="HPK_8in_198ch_2019_N4792_18_0324iv_dict2022_FullRetest_IV.txt"
    filename=args.f

    #FOR TESTING, USE THE FILES BELOW
    # if PRESERIES:
        # filename="HPK_8in_198ch_2019_200144_20220823_test1_IV.txt"
    # else:
        # filename="HPK_8in_198ch_2019_N4792_18_03242022_FullRetest_IV.txt"
    #i.e. you can test just this file by doing, eg.
    #python TXT_TO_XML.py --f HPK_8in_198ch_2019_200144_20220823_test1_IV.txt --t HGC_CERN_SENSOR_IV_SUMRY
    if args.t == 'HGC_CERN_SENSOR_IV':
        make_xml_schema_HGC_CERN_SENSOR_IV(filename)
    elif args.t == 'HGC_CERN_SENSOR_CV':
        make_xml_schema_HGC_CERN_SENSOR_CV(filename)
    elif args.t == 'HGC_CERN_SENSOR_IV_SUMRY':
        make_xml_schema_HGC_CERN_SENSOR_IV_SUMRY(filename)
