select * from CMS_HGC_CORE_MANAGEMNT.CONDITIONS_DATA_AUDITLOG where RECORD_LASTUPDATE_USER LIKE 'Ali%' ORDER BY RECORD_INSERTION_TIME DESC;

--select * from CMS_HGC_HGCAL_COND.HGC_CERN_SENSOR_IV_SUMRY;